/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol

// Source: ../sanity.schema.json
export type PageReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'page'
}

export type PostReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'post'
}

export type Link = {
  _type: 'link'
  linkType?: 'href' | 'page' | 'post'
  href?: string
  page?: PageReference
  post?: PostReference
  openInNewTab?: boolean
}

export type SanityImageAssetReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'sanity.imageAsset'
}

export type CallToAction = {
  _type: 'callToAction'
  eyebrow?: string
  heading: string
  body?: BlockContentTextOnly
  button?: Button
  image?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    _type: 'image'
  }
  theme?: 'light' | 'dark'
  contentAlignment?: 'textFirst' | 'imageFirst'
}

export type InfoSection = {
  _type: 'infoSection'
  heading?: string
  subheading?: string
  content?: BlockContent
}

export type BlockContentTextOnly = Array<{
  children?: Array<{
    marks?: Array<string>
    text?: string
    _type: 'span'
    _key: string
  }>
  style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
  listItem?: 'bullet' | 'number'
  markDefs?: Array<{
    href?: string
    _type: 'link'
    _key: string
  }>
  level?: number
  _type: 'block'
  _key: string
}>

export type BlockContent = Array<
  | {
      children?: Array<{
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }>
      style?: 'normal' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'blockquote'
      listItem?: 'bullet' | 'number'
      markDefs?: Array<{
        linkType?: 'href' | 'page' | 'post'
        href?: string
        page?: PageReference
        post?: PostReference
        openInNewTab?: boolean
        _type: 'link'
        _key: string
      }>
      level?: number
      _type: 'block'
      _key: string
    }
  | {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      _type: 'image'
      _key: string
    }
>

export type Button = {
  _type: 'button'
  buttonText?: string
  link?: Link
}

export type PersonReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'person'
}

export type CareAlert = {
  _id: string
  _type: 'careAlert'
  _createdAt: string
  _updatedAt: string
  _rev: string
  patient: PersonReference
  type: 'medical_emergency' | 'safety_hazard' | 'distress' | 'missed_medication' | 'other'
  description?: string
  status: 'open' | 'acknowledged' | 'resolved'
  raisedAt: string
  source?: 'anchor' | 'kiosk' | 'caregiver'
  acknowledgedBy?: PersonReference
  resolutionNote?: string
}

export type MedicationOrderReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'medicationOrder'
}

export type MedicationOrder = {
  _id: string
  _type: 'medicationOrder'
  _createdAt: string
  _updatedAt: string
  _rev: string
  patient: PersonReference
  name: string
  dosage: string
  steps: Array<string>
  effectiveFrom: string
  supersedes?: MedicationOrderReference
  changeNote?: string
  prescribedBy?: string
}

export type Visit = {
  _id: string
  _type: 'visit'
  _createdAt: string
  _updatedAt: string
  _rev: string
  patient: PersonReference
  visitor: PersonReference
  start: string
  end?: string
  purpose?: string
  status: 'scheduled' | 'cancelled'
}

export type KioskSettings = {
  _id: string
  _type: 'kioskSettings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  showChatCompanion?: boolean
  kioskTheme: 'dark' | 'light' | 'high-contrast'
  customWelcomeText?: string
}

export type CognitiveLog = {
  _id: string
  _type: 'cognitiveLog'
  _createdAt: string
  _updatedAt: string
  _rev: string
  patient: PersonReference
  quizDate: string
  gameType: 'Face-Name Match' | 'Trivia Anchor' | 'Music & Memory' | 'Pattern Recall'
  score: {
    correctAnswers: number
    totalQuestions: number
  }
  accuracyRate?: number
  patientResponseState: 'Calm/Engaged' | 'Frustrated/Anxious' | 'Distracted'
  caregiverNotes?: string
}

export type DailyChore = {
  _id: string
  _type: 'dailyChore'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  patient: PersonReference
  scheduledTime: string
  timeOfDay?: 'morning' | 'afternoon' | 'evening' | 'bedtime' | 'as_needed'
  instructions?: string
  safetyParameters?: {
    requiresSupervision?: boolean
    assistanceLevel?: 'independent' | 'verbal_cue' | 'standby' | 'full_assistance'
    priority?: 'routine' | 'important' | 'critical'
    safetyNotes?: string
  }
  completions?: Array<{
    completedAt: string
    status: 'completed' | 'partially_completed' | 'declined' | 'missed'
    recordedBy?: PersonReference
    notes?: string
    _type: 'completionRecord'
    _key: string
  }>
}

export type Settings = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
}

export type SanityImageCrop = {
  _type: 'sanity.imageCrop'
  top: number
  bottom: number
  left: number
  right: number
}

export type SanityImageHotspot = {
  _type: 'sanity.imageHotspot'
  x: number
  y: number
  height: number
  width: number
}

export type Page = {
  _id: string
  _type: 'page'
  _createdAt: string
  _updatedAt: string
  _rev: string
  name: string
  slug: Slug
  heading: string
  subheading?: string
  pageBuilder?: Array<
    | ({
        _key: string
      } & CallToAction)
    | ({
        _key: string
      } & InfoSection)
  >
}

export type Post = {
  _id: string
  _type: 'post'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  slug: Slug
  content?: BlockContent
  excerpt?: string
  coverImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  date?: string
  author?: PersonReference
}

export type Person = {
  _id: string
  _type: 'person'
  _createdAt: string
  _updatedAt: string
  _rev: string
  isPatient?: boolean
  slug?: Slug
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  relationship?: string
  patient?: PersonReference
  phoneNumber?: string
  coreMemories?: Array<{
    title: string
    storyText: string
    year?: string
    _type: 'memory'
    _key: string
  }>
}

export type Slug = {
  _type: 'slug'
  current: string
  source?: string
}

export type SanityAssistInstructionTask = {
  _type: 'sanity.assist.instructionTask'
  path?: string
  instructionKey?: string
  started?: string
  updated?: string
  info?: string
}

export type SanityAssistTaskStatus = {
  _type: 'sanity.assist.task.status'
  tasks?: Array<
    {
      _key: string
    } & SanityAssistInstructionTask
  >
}

export type SanityAssistSchemaTypeAnnotations = {
  _type: 'sanity.assist.schemaType.annotations'
  title?: string
  fields?: Array<
    {
      _key: string
    } & SanityAssistSchemaTypeField
  >
}

export type SanityAssistOutputType = {
  _type: 'sanity.assist.output.type'
  type?: string
}

export type SanityAssistOutputField = {
  _type: 'sanity.assist.output.field'
  path?: string
}

export type AssistInstructionContextReference = {
  _ref: string
  _type: 'reference'
  _weak?: boolean
  [internalGroqTypeReferenceTo]?: 'assist.instruction.context'
}

export type SanityAssistInstructionContext = {
  _type: 'sanity.assist.instruction.context'
  reference: AssistInstructionContextReference
}

export type AssistInstructionContext = {
  _id: string
  _type: 'assist.instruction.context'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title?: string
  context?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: null
    level?: number
    _type: 'block'
    _key: string
  }>
}

export type SanityAssistInstructionUserInput = {
  _type: 'sanity.assist.instruction.userInput'
  message: string
  description?: string
}

export type SanityAssistInstructionPrompt = Array<{
  children?: Array<
    | {
        marks?: Array<string>
        text?: string
        _type: 'span'
        _key: string
      }
    | ({
        _key: string
      } & SanityAssistInstructionFieldRef)
    | ({
        _key: string
      } & SanityAssistInstructionContext)
    | ({
        _key: string
      } & SanityAssistInstructionUserInput)
  >
  style?: 'normal'
  listItem?: never
  markDefs?: null
  level?: number
  _type: 'block'
  _key: string
}>

export type SanityAssistInstructionFieldRef = {
  _type: 'sanity.assist.instruction.fieldRef'
  path?: string
}

export type SanityAssistInstruction = {
  _type: 'sanity.assist.instruction'
  prompt?: SanityAssistInstructionPrompt
  icon?: string
  title?: string
  userId?: string
  createdById?: string
  output?: Array<
    | ({
        _key: string
      } & SanityAssistOutputField)
    | ({
        _key: string
      } & SanityAssistOutputType)
  >
}

export type SanityAssistSchemaTypeField = {
  _type: 'sanity.assist.schemaType.field'
  path?: string
  instructions?: Array<
    {
      _key: string
    } & SanityAssistInstruction
  >
}

export type SanityImagePaletteSwatch = {
  _type: 'sanity.imagePaletteSwatch'
  background?: string
  foreground?: string
  population?: number
  title?: string
}

export type SanityImagePalette = {
  _type: 'sanity.imagePalette'
  darkMuted?: SanityImagePaletteSwatch
  lightVibrant?: SanityImagePaletteSwatch
  darkVibrant?: SanityImagePaletteSwatch
  vibrant?: SanityImagePaletteSwatch
  dominant?: SanityImagePaletteSwatch
  lightMuted?: SanityImagePaletteSwatch
  muted?: SanityImagePaletteSwatch
}

export type SanityImageDimensions = {
  _type: 'sanity.imageDimensions'
  height: number
  width: number
  aspectRatio: number
}

export type SanityImageMetadata = {
  _type: 'sanity.imageMetadata'
  location?: Geopoint
  dimensions?: SanityImageDimensions
  palette?: SanityImagePalette
  lqip?: string
  blurHash?: string
  thumbHash?: string
  hasAlpha?: boolean
  isOpaque?: boolean
}

export type SanityFileAsset = {
  _id: string
  _type: 'sanity.fileAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  source?: SanityAssetSourceData
}

export type SanityAssetSourceData = {
  _type: 'sanity.assetSourceData'
  name?: string
  id?: string
  url?: string
}

export type SanityImageAsset = {
  _id: string
  _type: 'sanity.imageAsset'
  _createdAt: string
  _updatedAt: string
  _rev: string
  originalFilename?: string
  label?: string
  title?: string
  description?: string
  altText?: string
  sha1hash: string
  extension: string
  mimeType: string
  size: number
  assetId: string
  uploadId?: string
  path: string
  url: string
  metadata?: SanityImageMetadata
  source?: SanityAssetSourceData
}

export type Geopoint = {
  _type: 'geopoint'
  lat?: number
  lng?: number
  alt?: number
}

export type AllSanitySchemaTypes =
  | PageReference
  | PostReference
  | Link
  | SanityImageAssetReference
  | CallToAction
  | InfoSection
  | BlockContentTextOnly
  | BlockContent
  | Button
  | PersonReference
  | CareAlert
  | MedicationOrderReference
  | MedicationOrder
  | Visit
  | KioskSettings
  | CognitiveLog
  | DailyChore
  | Settings
  | SanityImageCrop
  | SanityImageHotspot
  | Page
  | Post
  | Person
  | Slug
  | SanityAssistInstructionTask
  | SanityAssistTaskStatus
  | SanityAssistSchemaTypeAnnotations
  | SanityAssistOutputType
  | SanityAssistOutputField
  | AssistInstructionContextReference
  | SanityAssistInstructionContext
  | AssistInstructionContext
  | SanityAssistInstructionUserInput
  | SanityAssistInstructionPrompt
  | SanityAssistInstructionFieldRef
  | SanityAssistInstruction
  | SanityAssistSchemaTypeField
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint

// Source: sanity/lib/queries.ts
// Variable: settingsQuery
// Query: *[_type == "settings"][0]
export type SettingsQueryResult = {
  _id: string
  _type: 'settings'
  _createdAt: string
  _updatedAt: string
  _rev: string
  title: string
  description?: Array<{
    children?: Array<{
      marks?: Array<string>
      text?: string
      _type: 'span'
      _key: string
    }>
    style?: 'normal'
    listItem?: never
    markDefs?: Array<{
      linkType?: 'href' | 'page' | 'post'
      href?: string
      page?: PageReference
      post?: PostReference
      openInNewTab?: boolean
      _type: 'link'
      _key: string
    }>
    level?: number
    _type: 'block'
    _key: string
  }>
  ogImage?: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    metadataBase?: string
    _type: 'image'
  }
} | null

// Source: sanity/lib/queries.ts
// Variable: kioskSettingsQuery
// Query: *[_type == "kioskSettings"][0] {    showChatCompanion,    kioskTheme,    customWelcomeText,  }
export type KioskSettingsQueryResult = {
  showChatCompanion: boolean | null
  kioskTheme: 'dark' | 'high-contrast' | 'light'
  customWelcomeText: string | null
} | null

// Source: sanity/lib/queries.ts
// Variable: getPageQuery
// Query: *[_type == 'page' && slug.current == $slug][0]{    _id,    _type,    name,    slug,    heading,    subheading,    "pageBuilder": pageBuilder[]{      ...,      _type == "callToAction" => {        ...,        button {          ...,            link {      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }      }        }      },      _type == "infoSection" => {        content[]{          ...,          markDefs[]{            ...,              _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }          }        }      },    },  }
export type GetPageQueryResult = {
  _id: string
  _type: 'page'
  name: string
  slug: Slug
  heading: string
  subheading: string | null
  pageBuilder: Array<
    | {
        _key: string
        _type: 'callToAction'
        eyebrow?: string
        heading: string
        body?: BlockContentTextOnly
        button: {
          _type: 'button'
          buttonText?: string
          link: {
            _type: 'link'
            linkType?: 'href' | 'page' | 'post'
            href?: string
            page: string | null
            post: string | null
            openInNewTab?: boolean
          } | null
        } | null
        image?: {
          asset?: SanityImageAssetReference
          media?: unknown
          hotspot?: SanityImageHotspot
          crop?: SanityImageCrop
          _type: 'image'
        }
        theme?: 'dark' | 'light'
        contentAlignment?: 'imageFirst' | 'textFirst'
      }
    | {
        _key: string
        _type: 'infoSection'
        heading?: string
        subheading?: string
        content: Array<
          | {
              children?: Array<{
                marks?: Array<string>
                text?: string
                _type: 'span'
                _key: string
              }>
              style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
              listItem?: 'bullet' | 'number'
              markDefs: Array<{
                linkType?: 'href' | 'page' | 'post'
                href?: string
                page: string | null
                post: string | null
                openInNewTab?: boolean
                _type: 'link'
                _key: string
              }> | null
              level?: number
              _type: 'block'
              _key: string
            }
          | {
              asset?: SanityImageAssetReference
              media?: unknown
              hotspot?: SanityImageHotspot
              crop?: SanityImageCrop
              _type: 'image'
              _key: string
              markDefs: null
            }
        > | null
      }
  > | null
} | null

// Source: sanity/lib/queries.ts
// Variable: sitemapData
// Query: *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {    "slug": slug.current,    _type,    _updatedAt,  }
export type SitemapDataResult = Array<
  | {
      slug: string
      _type: 'page'
      _updatedAt: string
    }
  | {
      slug: string
      _type: 'post'
      _updatedAt: string
    }
>

// Source: sanity/lib/queries.ts
// Variable: allPostsQuery
// Query: *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type AllPostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: morePostsQuery
// Query: *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type MorePostsQueryResult = Array<{
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: postQuery
// Query: *[_type == "post" && slug.current == $slug] [0] {    content[]{    ...,    markDefs[]{      ...,        _type == "link" => {    "page": page->slug.current,    "post": post->slug.current  }    }  },      _id,  "status": select(_originalId in path("drafts.**") => "draft", "published"),  "title": coalesce(title, "Untitled"),  "slug": slug.current,  excerpt,  coverImage,  "date": coalesce(date, _updatedAt),  "author": author->{firstName, lastName, picture},  }
export type PostQueryResult = {
  content: Array<
    | {
        children?: Array<{
          marks?: Array<string>
          text?: string
          _type: 'span'
          _key: string
        }>
        style?: 'blockquote' | 'h1' | 'h2' | 'h3' | 'h4' | 'h5' | 'h6' | 'normal'
        listItem?: 'bullet' | 'number'
        markDefs: Array<{
          linkType?: 'href' | 'page' | 'post'
          href?: string
          page: string | null
          post: string | null
          openInNewTab?: boolean
          _type: 'link'
          _key: string
        }> | null
        level?: number
        _type: 'block'
        _key: string
      }
    | {
        asset?: SanityImageAssetReference
        media?: unknown
        hotspot?: SanityImageHotspot
        crop?: SanityImageCrop
        _type: 'image'
        _key: string
        markDefs: null
      }
  > | null
  _id: string
  status: 'draft' | 'published'
  title: string
  slug: string
  excerpt: string | null
  coverImage: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  } | null
  date: string
  author: {
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
  } | null
} | null

// Source: sanity/lib/queries.ts
// Variable: postPagesSlugs
// Query: *[_type == "post" && defined(slug.current)]  {"slug": slug.current}
export type PostPagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: pagesSlugs
// Query: *[_type == "page" && defined(slug.current)]  {"slug": slug.current}
export type PagesSlugsResult = Array<{
  slug: string
}>

// Source: sanity/lib/queries.ts
// Variable: dailyChoresQuery
// Query: *[_type == "dailyChore"] | order(scheduledTime asc) {    _id,    _type,    title,    scheduledTime,    timeOfDay,    instructions,    safetyParameters {      requiresSupervision,      assistanceLevel,      priority,      safetyNotes    },    completions[] {      completedAt,      status,      notes,      _key    },    patient-> {      _id,      firstName,      lastName    }  }
export type DailyChoresQueryResult = Array<{
  _id: string
  _type: 'dailyChore'
  title: string
  scheduledTime: string
  timeOfDay: 'afternoon' | 'as_needed' | 'bedtime' | 'evening' | 'morning' | null
  instructions: string | null
  safetyParameters: {
    requiresSupervision: boolean | null
    assistanceLevel: 'full_assistance' | 'independent' | 'standby' | 'verbal_cue' | null
    priority: 'critical' | 'important' | 'routine' | null
    safetyNotes: string | null
  } | null
  completions: Array<{
    completedAt: string
    status: 'completed' | 'declined' | 'missed' | 'partially_completed'
    notes: string | null
    _key: string
  }> | null
  patient: {
    _id: string
    firstName: string
    lastName: string
  }
}>

// Source: sanity/lib/queries.ts
// Variable: allPersonsQuery
// Query: *[_type == "person"] {    _id,    _type,    firstName,    lastName,    picture,    relationship,    phoneNumber,    isPatient,    "slug": slug.current,    coreMemories  }
export type AllPersonsQueryResult = Array<{
  _id: string
  _type: 'person'
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  relationship: string | null
  phoneNumber: string | null
  isPatient: boolean | null
  slug: string | null
  coreMemories: Array<{
    title: string
    storyText: string
    year?: string
    _type: 'memory'
    _key: string
  }> | null
}>

// Source: sanity/lib/queries.ts
// Variable: allPatientsQuery
// Query: *[_type == "person" && isPatient == true] | order(firstName asc) {    _id,    _type,    firstName,    lastName,    picture,    "slug": slug.current,    relationship,    isPatient,    "choreCount": count(*[_type == "dailyChore" && patient._ref == ^._id]),    "caregivers": *[_type == "person" && isPatient != true && patient._ref == ^._id] {      _id,      _type,      firstName,      lastName,      picture,      relationship,      "relationshipToPatient": relationship,      phoneNumber    }  }
export type AllPatientsQueryResult = Array<{
  _id: string
  _type: 'person'
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slug: string | null
  relationship: string | null
  isPatient: true
  choreCount: number
  caregivers: Array<{
    _id: string
    _type: 'person'
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    relationship: string | null
    relationshipToPatient: string | null
    phoneNumber: string | null
  }>
}>

// Source: sanity/lib/queries.ts
// Variable: patientByIdOrSlugQuery
// Query: *[_type == "person" && (    _id == $id ||    slug.current == $id ||    slug.current == "/" + $id ||    slug.current == "/kiosk/" + $id ||    slug.current == "kiosk/" + $id  )][0] {    _id,    _type,    firstName,    lastName,    picture,    "slug": slug.current,    relationship,    isPatient,    coreMemories,    patient-> {      _id,      firstName,      lastName,      "slug": slug.current    },    "caregivers": *[_type == "person" && isPatient != true && patient._ref == ^._id] {      _id,      _type,      firstName,      lastName,      picture,      relationship,      "relationshipToPatient": relationship,      phoneNumber    }  }
export type PatientByIdOrSlugQueryResult = {
  _id: string
  _type: 'person'
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  slug: string | null
  relationship: string | null
  isPatient: boolean | null
  coreMemories: Array<{
    title: string
    storyText: string
    year?: string
    _type: 'memory'
    _key: string
  }> | null
  patient: {
    _id: string
    firstName: string
    lastName: string
    slug: string | null
  } | null
  caregivers: Array<{
    _id: string
    _type: 'person'
    firstName: string
    lastName: string
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    relationship: string | null
    relationshipToPatient: string | null
    phoneNumber: string | null
  }>
} | null

// Source: sanity/lib/queries.ts
// Variable: connectedCaregiversByPatientQuery
// Query: *[_type == "person" && isPatient != true && patient._ref == $patientId] {    _id,    _type,    firstName,    lastName,    picture,    relationship,    "relationshipToPatient": relationship,    phoneNumber  }
export type ConnectedCaregiversByPatientQueryResult = Array<{
  _id: string
  _type: 'person'
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  relationship: string | null
  relationshipToPatient: string | null
  phoneNumber: string | null
}>

// Source: sanity/lib/queries.ts
// Variable: dailyChoresByPatientQuery
// Query: *[_type == "dailyChore" && (    patient._ref == $patientId ||    patient->slug.current == $patientId ||    patient->slug.current == "/" + $patientId ||    patient->slug.current == "/kiosk/" + $patientId ||    patient->slug.current == "kiosk/" + $patientId  )] | order(scheduledTime asc) {    _id,    _type,    title,    scheduledTime,    timeOfDay,    instructions,    safetyParameters {      requiresSupervision,      assistanceLevel,      priority,      safetyNotes    },    completions[] {      completedAt,      status,      notes,      _key    },    patient-> {      _id,      firstName,      lastName    }  }
export type DailyChoresByPatientQueryResult = Array<{
  _id: string
  _type: 'dailyChore'
  title: string
  scheduledTime: string
  timeOfDay: 'afternoon' | 'as_needed' | 'bedtime' | 'evening' | 'morning' | null
  instructions: string | null
  safetyParameters: {
    requiresSupervision: boolean | null
    assistanceLevel: 'full_assistance' | 'independent' | 'standby' | 'verbal_cue' | null
    priority: 'critical' | 'important' | 'routine' | null
    safetyNotes: string | null
  } | null
  completions: Array<{
    completedAt: string
    status: 'completed' | 'declined' | 'missed' | 'partially_completed'
    notes: string | null
    _key: string
  }> | null
  patient: {
    _id: string
    firstName: string
    lastName: string
  }
}>

// Source: sanity/lib/queries.ts
// Variable: familyMembersByPatientQuery
// Query: *[_type == "person" && _id != $patientId && patient._ref == $patientId] {    _id,    _type,    firstName,    lastName,    picture,    relationship,    phoneNumber,    coreMemories  }
export type FamilyMembersByPatientQueryResult = Array<{
  _id: string
  _type: 'person'
  firstName: string
  lastName: string
  picture: {
    asset?: SanityImageAssetReference
    media?: unknown
    hotspot?: SanityImageHotspot
    crop?: SanityImageCrop
    alt?: string
    _type: 'image'
  }
  relationship: string | null
  phoneNumber: string | null
  coreMemories: Array<{
    title: string
    storyText: string
    year?: string
    _type: 'memory'
    _key: string
  }> | null
}>

// Source: sanity/lib/queries.ts
// Variable: visitsByPatientQuery
// Query: *[_type == "visit" && patient._ref == $patientId && status != "cancelled"    && dateTime(start) >= dateTime($dayStart) && dateTime(start) < dateTime($dayEnd)]    | order(start asc) {    _id,    start,    end,    purpose,    visitor-> { _id, firstName, lastName, relationship, picture, "memories": coreMemories[0...2] }  }
export type VisitsByPatientQueryResult = Array<{
  _id: string
  start: string
  end: string | null
  purpose: string | null
  visitor: {
    _id: string
    firstName: string
    lastName: string
    relationship: string | null
    picture: {
      asset?: SanityImageAssetReference
      media?: unknown
      hotspot?: SanityImageHotspot
      crop?: SanityImageCrop
      alt?: string
      _type: 'image'
    }
    memories: Array<{
      title: string
      storyText: string
      year?: string
      _type: 'memory'
      _key: string
    }> | null
  }
}>

// Source: sanity/lib/queries.ts
// Variable: currentMedicationOrdersQuery
// Query: *[_type == "medicationOrder" && patient._ref == $patientId    && dateTime(effectiveFrom) <= dateTime(now())    && count(*[_type == "medicationOrder" && supersedes._ref == ^._id && dateTime(effectiveFrom) <= dateTime(now())]) == 0] {    _id,    name,    dosage,    steps,    effectiveFrom,    changeNote,    "replaces": supersedes-> { name, effectiveFrom }  }
export type CurrentMedicationOrdersQueryResult = Array<{
  _id: string
  name: string
  dosage: string
  steps: Array<string>
  effectiveFrom: string
  changeNote: string | null
  replaces: {
    name: string
    effectiveFrom: string
  } | null
}>

// Source: sanity/lib/queries.ts
// Variable: openCareAlertsQuery
// Query: *[_type == "careAlert" && status == "open"] | order(raisedAt desc) {    _id,    type,    description,    raisedAt,    patient-> { _id, firstName, lastName }  }
export type OpenCareAlertsQueryResult = Array<{
  _id: string
  type: 'distress' | 'medical_emergency' | 'missed_medication' | 'other' | 'safety_hazard'
  description: string | null
  raisedAt: string
  patient: {
    _id: string
    firstName: string
    lastName: string
  }
}>

// Query TypeMap
import '@sanity/client'
declare module '@sanity/client' {
  interface SanityQueries {
    '*[_type == "settings"][0]': SettingsQueryResult
    '\n  *[_type == "kioskSettings"][0] {\n    showChatCompanion,\n    kioskTheme,\n    customWelcomeText,\n  }\n': KioskSettingsQueryResult
    '\n  *[_type == \'page\' && slug.current == $slug][0]{\n    _id,\n    _type,\n    name,\n    slug,\n    heading,\n    subheading,\n    "pageBuilder": pageBuilder[]{\n      ...,\n      _type == "callToAction" => {\n        ...,\n        button {\n          ...,\n          \n  link {\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n      }\n\n        }\n      },\n      _type == "infoSection" => {\n        content[]{\n          ...,\n          markDefs[]{\n            ...,\n            \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n          }\n        }\n      },\n    },\n  }\n': GetPageQueryResult
    '\n  *[_type == "page" || _type == "post" && defined(slug.current)] | order(_type asc) {\n    "slug": slug.current,\n    _type,\n    _updatedAt,\n  }\n': SitemapDataResult
    '\n  *[_type == "post" && defined(slug.current)] | order(date desc, _updatedAt desc) {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': AllPostsQueryResult
    '\n  *[_type == "post" && _id != $skip && defined(slug.current)] | order(date desc, _updatedAt desc) [0...$limit] {\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': MorePostsQueryResult
    '\n  *[_type == "post" && slug.current == $slug] [0] {\n    content[]{\n    ...,\n    markDefs[]{\n      ...,\n      \n  _type == "link" => {\n    "page": page->slug.current,\n    "post": post->slug.current\n  }\n\n    }\n  },\n    \n  _id,\n  "status": select(_originalId in path("drafts.**") => "draft", "published"),\n  "title": coalesce(title, "Untitled"),\n  "slug": slug.current,\n  excerpt,\n  coverImage,\n  "date": coalesce(date, _updatedAt),\n  "author": author->{firstName, lastName, picture},\n\n  }\n': PostQueryResult
    '\n  *[_type == "post" && defined(slug.current)]\n  {"slug": slug.current}\n': PostPagesSlugsResult
    '\n  *[_type == "page" && defined(slug.current)]\n  {"slug": slug.current}\n': PagesSlugsResult
    '\n  *[_type == "dailyChore"] | order(scheduledTime asc) {\n    _id,\n    _type,\n    title,\n    scheduledTime,\n    timeOfDay,\n    instructions,\n    safetyParameters {\n      requiresSupervision,\n      assistanceLevel,\n      priority,\n      safetyNotes\n    },\n    completions[] {\n      completedAt,\n      status,\n      notes,\n      _key\n    },\n    patient-> {\n      _id,\n      firstName,\n      lastName\n    }\n  }\n': DailyChoresQueryResult
    '\n  *[_type == "person"] {\n    _id,\n    _type,\n    firstName,\n    lastName,\n    picture,\n    relationship,\n    phoneNumber,\n    isPatient,\n    "slug": slug.current,\n    coreMemories\n  }\n': AllPersonsQueryResult
    '\n  *[_type == "person" && isPatient == true] | order(firstName asc) {\n    _id,\n    _type,\n    firstName,\n    lastName,\n    picture,\n    "slug": slug.current,\n    relationship,\n    isPatient,\n    "choreCount": count(*[_type == "dailyChore" && patient._ref == ^._id]),\n    "caregivers": *[_type == "person" && isPatient != true && patient._ref == ^._id] {\n      _id,\n      _type,\n      firstName,\n      lastName,\n      picture,\n      relationship,\n      "relationshipToPatient": relationship,\n      phoneNumber\n    }\n  }\n': AllPatientsQueryResult
    '\n  *[_type == "person" && (\n    _id == $id ||\n    slug.current == $id ||\n    slug.current == "/" + $id ||\n    slug.current == "/kiosk/" + $id ||\n    slug.current == "kiosk/" + $id\n  )][0] {\n    _id,\n    _type,\n    firstName,\n    lastName,\n    picture,\n    "slug": slug.current,\n    relationship,\n    isPatient,\n    coreMemories,\n    patient-> {\n      _id,\n      firstName,\n      lastName,\n      "slug": slug.current\n    },\n    "caregivers": *[_type == "person" && isPatient != true && patient._ref == ^._id] {\n      _id,\n      _type,\n      firstName,\n      lastName,\n      picture,\n      relationship,\n      "relationshipToPatient": relationship,\n      phoneNumber\n    }\n  }\n': PatientByIdOrSlugQueryResult
    '\n  *[_type == "person" && isPatient != true && patient._ref == $patientId] {\n    _id,\n    _type,\n    firstName,\n    lastName,\n    picture,\n    relationship,\n    "relationshipToPatient": relationship,\n    phoneNumber\n  }\n': ConnectedCaregiversByPatientQueryResult
    '\n  *[_type == "dailyChore" && (\n    patient._ref == $patientId ||\n    patient->slug.current == $patientId ||\n    patient->slug.current == "/" + $patientId ||\n    patient->slug.current == "/kiosk/" + $patientId ||\n    patient->slug.current == "kiosk/" + $patientId\n  )] | order(scheduledTime asc) {\n    _id,\n    _type,\n    title,\n    scheduledTime,\n    timeOfDay,\n    instructions,\n    safetyParameters {\n      requiresSupervision,\n      assistanceLevel,\n      priority,\n      safetyNotes\n    },\n    completions[] {\n      completedAt,\n      status,\n      notes,\n      _key\n    },\n    patient-> {\n      _id,\n      firstName,\n      lastName\n    }\n  }\n': DailyChoresByPatientQueryResult
    '\n  *[_type == "person" && _id != $patientId && patient._ref == $patientId] {\n    _id,\n    _type,\n    firstName,\n    lastName,\n    picture,\n    relationship,\n    phoneNumber,\n    coreMemories\n  }\n': FamilyMembersByPatientQueryResult
    '\n  *[_type == "visit" && patient._ref == $patientId && status != "cancelled"\n    && dateTime(start) >= dateTime($dayStart) && dateTime(start) < dateTime($dayEnd)]\n    | order(start asc) {\n    _id,\n    start,\n    end,\n    purpose,\n    visitor-> { _id, firstName, lastName, relationship, picture, "memories": coreMemories[0...2] }\n  }\n': VisitsByPatientQueryResult
    '\n  *[_type == "medicationOrder" && patient._ref == $patientId\n    && dateTime(effectiveFrom) <= dateTime(now())\n    && count(*[_type == "medicationOrder" && supersedes._ref == ^._id && dateTime(effectiveFrom) <= dateTime(now())]) == 0] {\n    _id,\n    name,\n    dosage,\n    steps,\n    effectiveFrom,\n    changeNote,\n    "replaces": supersedes-> { name, effectiveFrom }\n  }\n': CurrentMedicationOrdersQueryResult
    '\n  *[_type == "careAlert" && status == "open"] | order(raisedAt desc) {\n    _id,\n    type,\n    description,\n    raisedAt,\n    patient-> { _id, firstName, lastName }\n  }\n': OpenCareAlertsQueryResult
  }
}
